run = "run1"
dirname = "wavetool"
profile = "data/profile.msgpack"
overwrite = true

[analyze]
rawfile = "wavetool"
wavefile = "wavefilter"
fc_low = 0.5
order = 4

[plot]
wavefile = "wavefilter"
output = "wavefilter"
fps = 10
B_wave_lim = [-0.25, 0.25]
B_env_lim = [0.0, 0.5]
B_abs_lim = [0.5, 5.0]
S_para_lim = [-0.5, 0.5]
